---
title: "Curriculo Tales"
author: Tales Gomes
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
#
#Abaixo para mudar da verão Html para PDF (Precisa ser automatizado)
#
#A versão em pdf deste currículo pode ser encontrada #[**aqui**](https://github.com/rstudio/pagedown).
#
#A versão *on-line* deste currículo pode ser encontrada #[**aqui**](https://github.com/rstudio/pagedown).
#
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print

#Objetivo
#Meu objetivo é realizar minha transição de carreira: do serviço público para a análise de dados. Na XP, como  *business analyst*, vislumbro a possibilidade de trabalhar em um ambiente em que haja valorização do pensamento analítico, do uso da lógica e da matemática, do trabalho em equipe, da definição de metas claras e coerentes com a visão, missão e valores da empresa, com os quais me identifico. Precisei passar os últimos anos trabalhando no serviço público, pois ainda na graduação o concurso surgiu como uma oportunidade de suporte financeiro. Contudo, após o término do curso de engenharia da computação, permaneci no cargo público, sem abrir mão de dar continuidade na minha qualificação voltada para a área de dados. Na atual posição profissional percebo que já explorei todas as vias de desenvolvimento, porém preciso de mais, de novos desafios. Como engenheiro da computação sempre fui fascinado por números e resolução de problemas e me candidato a presente vaga de *business analyst* com a expectativa de evoluir, progredir e agregar.



---

# Aside

## Contatos {#contact}

-   <i class="fas fa-map-marker-alt"></i> `Belém, Pará, Brasil.`
-   <i class="fa fa-envelope"></i> [talesgomes27@gmail.com](mailto:talesgomes27@gmail.com){.email}
-   <i class="fa fa-github"></i> [github.com/talesgomes27](https://github.com/talesgomes27)
-   <i class="fa fa-linkedin"></i> [linkedin.com/in/talesgomes27](https://www.linkedin.com/in/talesgomes27/)
-   <i class="fas fa-globe"></i> [blogdotales.netlify.app](https://blogdotales.netlify.app/)
-   <i class="fa fa-phone"></i> +55 91 98406-9826
-   Para mais infirmações, entre em contato por e-mail.


## Habilidades {#skills}

 
-   <i class="fab fa-r-project"></i> `R`
-   <i class="fas fa-database"></i> `Sql`
-   <i class="fas fa-table"></i> `Excel`
-   <i class="fab fa-python"></i> `Python`
-   <i class="fas fa-chart-line"></i> `Tableau`
-   <i class="fab fa-markdown"></i> `Markdown`
-   <i class="far fa-file-powerpoint"></i> `Power point`
-   <i class="fab fa-github"></i> `Github`
-   <i class="fab fa-linux"></i> `Linux`
-   <i class="fab fa-windows"></i> `Windows`

## Competências    {#skills}

-   <i class="fas fa-users"></i> `Trabalho em equipe`
-   <i class="fas fa-handshake"></i> `Responsabilidade`
-   <i class="far fa-compass"></i> `Capacidade de adaptação`
-   <i class="fas fa-chart-bar"></i> `Análise estatística de dados`
-   <i class="fas fa-calculator"></i> `Forte base matemática`
-   <i class="fas fa-user-cog"></i> `Raciocínio rápido`
-   <i class="fas fa-user-check"></i> `Autonomia`


A versão *on-line* deste currículo pode ser encontrada [**aqui**](https://talesgomes27.github.io/curriculo/).

# Main

## Tales W. Gomes da Silva {#title}

### Business Analyst


## Experiência Profissional {data-icon="suitcase"}

### Servidor Público

Tribunal de Justiça do Estado do Pará

Pará, Brasil

2013 - Atualmente

::: {.concise}
-   Atendimento ao Público
-   Confecção de documentos: certidões, mandados, ofícios e outros.
-   Análise de processos judiciais.
:::


## Projetos {data-icon="chart-bar"}

### Bikeshare: uma empresa de compartilhamento de bicicletas.


Projeto desenvolvido para aquisição do certificado profissional em análise de dados, através da plataforma Coursera, sob a instrução da Google. Nele foram coletados, ao longo de 12 meses, dados acerca dos usuários membros assinantes do serviço oferecido pela empresa Bikeshare e usuários avulsos, de modo a identificar a diferença entre os dois grupos quanto a forma de utilização do serviço, visando à elaboração de recomendações para a equipe de marketing da empresa. 

::: {.concise}
-   [Link para o projeto](https://talesgomes27.github.io/DAC8-Case-Study-1/)
-   [link para o código](https://github.com/talesgomes27/DAC8-Case-Study-1)
:::

 
### Mulheres olímpicas no pós II Guerra Mundial: uma análise da participação feminina nas delegações brasileiras em olimpíadas no período de 1948 a 2016.


Análise realizada a partir do [tidytuesday](https://github.com/rfordatascience/tidytuesday), do ano de 2021, semana 31, que objetiva investigar a participação feminina olímpica do Brasil no período de 1948 a 2016 e como essa participação difere da média olímpica quando comparada a países pares.


::: {.concise}
-   [Link para o projeto](https://talesgomes27.github.io/tidytuesday/tidytuesday/2021-31/tidytuesday_2021-31.html)
-   [link para o código](https://github.com/talesgomes27/tidytuesday/tree/main/tidytuesday/2021-31)
:::

### Focos de incêndios no Brasil de 1998 a 2017.

Neste projeto utilizo o banco de dados do kaggle ([Forest Fires in Brazil](https://www.kaggle.com/gustavomodelli/forest-fires-in-brazil) que contém o número de focos de incêndios em florestas brasileiras do ano de 1998 até 2017, com objetivo de encontrar padrões nos dados, além de treinar visualizações com mapas e confecção de dashboards.



::: {.concise}
-   [Link para o projeto](https://talesgomes27.github.io/kaggle/kaggle/forest-fires-in-brazil/Forest_fires_in_Brazil.html)
-   [link para o código](https://github.com/talesgomes27/kaggle/tree/main/kaggle/forest-fires-in-brazil)
-   [link Tableau](https://public.tableau.com/app/profile/tales.gomes/viz/FocosdeincndiosnoBrasil1998a2017/FocosdeincndionoBrasil)
:::

### O caso Bellabeats.


Trabalho realizado buscando a melhoria do funcionamento do Fitibit, um fitness Tracker da Belabeats, através da identificação de tendências de uso. Para tanto foram analisados os dados contidos na base do kaggle [*FitBit Fitness Tracker Data*](https://www.kaggle.com/arashnic/fitbit) acerca de 33 usuários.


::: {.concise}
-   [Link para o projeto](https://blogdotales.netlify.app/post/2021-09-10-bellabeat/)
-   [link para o código](https://github.com/talesgomes27/blog/tree/main/content/blog/2021-09-10-bellabeat)
:::

## Cursos {data-icon="laptop"}

### Certificado Profissional em Análise de dados da Google.

Coursera/Google

[*on-line*](https://coursera.org/share/b8f00a8635126ef11eed8b4564c64cde)

2021



### As Ferramentas do Cientista de Dados

Coursera

[*on-line*](https://coursera.org/share/68bbd792642e5ab8fb9fecaff748c250)

2021


### Relatórios e visualização de dados.

Curso-r

[*on-line*](https://curso-r.com/cursos/visualizacao/)

2021

### Dashboards com Shiny

Curso-r

[*on-line*](https://curso-r.com/cursos/dashboards/)

Em andamento



## Formação {data-icon="graduation-cap" data-concise="true"}

### Bacharelado em Engenharia da Computação

Universidade Federal do Pará

Pará, Brasil

2009 - 2016


### Curso Técnico em Mecânica, integrado ao ensino médio.

Instituto Federal de Educação, Ciência e Tecnologia do Pará.

Pará, Brasil

2005 - 2008









